### OUTPUT / BACKGROUND ###

output * bg ~/.config/sway/bg/lonely_coding.png fill

### GAPS / APPEARANCE ###

# Gaps
gaps inner 15
gaps outer 20

# Borders
default_border pixel 2
default_floating_border pixel 2

# Colors
client.focused          #E95420 #E95420 #ffffff #E95420 #E95420
client.unfocused        #333333 #333333 #888888 #333333 #333333
client.focused_inactive #555555 #555555 #cccccc #555555 #555555
client.urgent           #ff0000 #ff0000 #ffffff #ff0000 #ff0000

### DISPLAY CONFIG ###
# Left monitor – DP-2, rotated 270°, 1920x1080 @ 100 Hz
#output DP-2 {
#    mode 1920x1080@100Hz
#    position 0 0
#    transform 270
#    scale 1
#}

# Center monitor – DP-1, ultrawide 3440x1440 @ 144 Hz
#output DP-1 {
#    mode 3440x1440@144Hz
#    position 1080 196
#    transform normal
#    scale 1
#}
